name: DBT
version: 1.0.0
config-version: 2
profile: DBT
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
models:
  DBT:
    staging:
      materialized: view
    mart:
      materialized: table

